### ISSUE TITLE
Version: 2021-03 (4.19.0) : when saving a .java file color resets

### ISSUE THREAD

**Issue by LuciferSam86** [PyvesB/eclipse-planet-themes#4] opened 2021-04-29 07:44 UTC
Hi,
when I save a .java file like this one
![immagine](https://user-images.githubusercontent.com/8456295/116517474-50123800-a8cf-11eb-8567-0cc9167ed243.png)

the color resets
![immagine](https://user-images.githubusercontent.com/8456295/116517528-64563500-a8cf-11eb-8747-f04b64d70a54.png)

I have to switch to another tab to restore the colors.

**Comment by PyvesB** [comment] 2021-04-29 20:16
Hello @LuciferSam86 ! 👋🏻 

Sorry to hear that the theme is not working as expected for you!

Am I correct in thinking that you're using a Windows machine?

I did bump into this problem at some point whilst testing on Windows, but only on some of my Eclipse installations and not others, and didn't really get to the bottom of it. I've got the gut feeling it's related to the flat scrollbars library this project is using, in particular this issue I encountered at the time: https://github.com/fappel/xiliary/issues/94

If you download the standalone Eclipse SDK (http://download.eclipse.org/eclipse/downloads/drops4/R-4.19-202103031800/download.php?dropFile=eclipse-SDK-4.19-win32-x86_64.zip), launch it in a new workspace and install the Planet themes via the update site (https://raw.githubusercontent.com/PyvesB/eclipse-planet-themes/updatesite), could you please confirm that the issue is **not** happening? The next step would be to determine what causes the issue to arise: is it having a specific view or perspective opened, a plugin installed, something else?

**Comment by LuciferSam86** [comment] 2021-05-04 15:12
Finally I was able to test the fix you suggested. 
So : the perspective is "Java", the version of the ide is the one for Java EE developers and I don't have any plugins installed (it's a fresh install) , and I still have the problem.

**Comment by PyvesB** [comment] 2021-05-08 11:33
> If you download the standalone Eclipse SDK (http://download.eclipse.org/eclipse/downloads/drops4/R-4.19-202103031800/download.php?dropFile=eclipse-SDK-4.19-win32-x86_64.zip), launch it in a new workspace and install the Planet themes via the update site (https://raw.githubusercontent.com/PyvesB/eclipse-planet-themes/updatesite), could you please confirm that the issue is **not** happening?

What about this? The IDE package for Java EE developers ships with **_many_** plugins. What would be really useful is to go from the standalone SDK, and install plugins to slowly recreate the fully blown Java EE developers IDE. At some point, I'm hoping the theming issue will start appearing, which will hopefully point to the plugin that is causing conflicts.

**Comment by PancakeTAS** [comment] 2021-11-11 17:18
I am facing the same issue on an eclipse installation with only JDT, Marketplace Client and Planet Themes installed.
Everytime I open a .java file (really any files does this) it will make the background white. Sometimes even with other Windows not only the selected one. Theme is Pluto

**Comment by PyvesB** [comment] 2021-11-14 15:15
It would be useful to check the following scenario :
* with the standalone Eclipse SDK, check that the issue does not happen on a non-Java file.
* after installing JDT, check whether the issue starts happening on the same non-Java file.

**Comment by PancakeTAS** [comment] 2021-11-14 15:17
Happens on a new Standalone Eclipse SDK even with a non-java file. Just opening it will make the screen appear white.
After installing JDT and saving a Java file, it resets the color too

**Comment by PyvesB** [comment] 2021-11-14 16:44
Hmmm, when I checked back in April, I couldn't reproduce on a standalone Eclipse SDK.

I've unfortunately not got much time to spare at the moment, if someone wants to investigate and contribute to the project, these files and discussions will probably be of interest:
* https://github.com/PyvesB/eclipse-planet-themes/blob/master/planet-themes-plugin/css/planets.css
* https://github.com/PyvesB/eclipse-planet-themes/blob/master/planet-themes-plugin/css/planets-win.css
* https://github.com/fappel/xiliary/issues/94

**Comment by PancakeTAS** [comment] 2021-11-14 18:11
Unfortunately it does not look like the issue has been fixed by that

**Comment by AnkitDeshpande** [comment] 2023-08-04 09:58
> Unfortunately it does not look like the issue has been fixed by that



> Happens on a new Standalone Eclipse SDK even with a non-java file. Just opening it will make the screen appear white. After installing JDT and saving a Java file, it resets the color too

If u have installed any other theme like "Darkest Dark". try uninstalling that. It worked for me, Idk if it work for u.

**Comment by PyvesB** [comment] 2024-01-07 21:46
Thinking out loud, I'm wondering whether this is not the same root cause as https://bugs.eclipse.org/bugs/show_bug.cgi?id=565754 which I reported a while back.

**Comment by PyvesB** [comment] 2024-06-16 16:38
I've decided to drop the flat scrollbars (5a69cebfe3cdba9eda7c685467cfd0f9ca60603c). This issue should no longer happen on version 0.3.0 of the plugin.

**Closed as completed by PyvesB** 2024-06-16 16:38 UTC
