### ISSUE TITLE
Cannot install the theme.

### ISSUE THREAD

**Issue by AnkitDeshpande** [PyvesB/eclipse-planet-themes#16] opened 2023-12-31 17:53 UTC
I tried to install the theme from marketplace and its constantly giving me an error.

"Cannot complete the install because one or more required items could not be found.
  Software being installed: Planet Themes 0.2.5.202202261537 (io.github.pyvesb.eclipse_planet_themes.feature.group 0.2.5.202202261537)
  Missing requirement: Planet Themes 0.2.5 (io.github.pyvesb.eclipse_planet_themes 0.2.5) requires 'osgi.bundle; javax.inject 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: Planet Themes 0.2.5.202202261537 (io.github.pyvesb.eclipse_planet_themes.feature.group 0.2.5.202202261537)
    To: org.eclipse.equinox.p2.iu; io.github.pyvesb.eclipse_planet_themes [0.2.5,0.2.5] "
    
    
this error is really annoying me can you tell me what should I do?

**Comment by PyvesB** [comment] 2023-12-31 18:37
Hello @AnkitDeshpande! 👋🏻 

Thanks for reporting. Are you using the latest version of Eclipse by any chance? I think this may be caused by https://eclipse.dev/eclipse/news/4.30/platform.php#support-jakarta-annotations

**Comment by PyvesB** [comment] 2024-01-01 12:29
This should be fixed in next release via 76bb27972d34228759011e96c30665a121471faf.

**Closed as completed by PyvesB** 2024-01-01 12:29 UTC
