### ISSUE TITLE
Both pluto and neptune is buggy.

### ISSUE THREAD

**Issue by AnkitDeshpande** [PyvesB/eclipse-planet-themes#14] opened 2023-07-23 23:33 UTC
Hi Pierre-Yves Bigourdan,

Its a nice themes. Pluto is my favourite but i guess its buggy. When i my project and click on class it shows white screen and when i click somewhere else  it return backs to normal. Im attaching images please take a look.
![Screenshot (37)](https://github.com/PyvesB/eclipse-planet-themes/assets/115605876/8fda43bf-7bef-4448-9933-09b1cb940943)

**Comment by MALossov** [comment] 2023-08-03 08:13
Same with TI's CCS

**Comment by AnkitDeshpande** [comment] 2023-08-03 08:45
> Same with TI's CCS

Neptune too. But i have fixed it somehow. Idk how it got fixed. i did some poking here and there and its fixed now.

**Comment by AnkitDeshpande** [comment] 2023-08-04 01:11
> Same with TI's CCS

Try uninstalling Darkest Dark theme, It worked for me. idk if it will work for u?

**Comment by PyvesB** [comment] 2023-08-04 07:35
Hello 👋🏻 

This looks like a duplicate of #4. If you've got more precise information on how to reproduce or want to help solve the issue, let's continue the discussion there. :)

**Closed as completed by PyvesB** 2023-08-04 07:35 UTC
